/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mamu' at '1/4/17 3:06 AM' with Gradle 2.11
 *
 * @author mamu, @date 1/4/17 3:06 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
